### ISSUE TITLE
When I run :python -m scripts.make_kfold_callhome $xvector_dir $KALDI_PATH/egs/callhome_diarization/v2/data/callhome/fullref.rttm $folds_path $num_folds

### ISSUE THREAD

**Issue by wenyuqing** [cvqluu/nn-similarity-diarization#3] opened 2020-10-21 02:40 UTC

**Comment by wenyuqing** [comment] 2020-10-21 02:42
I meet an error:
File "/home/xxx/nn-similarity-diarization-master/data_io.py", line 113, in make_k_fold_dataset
    splits = np.array_split(p, k)
  File "<__array_function__ internals>", line 6, in array_split
  File "/home/xxx/.conda/envs/37_torch_speech/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 790, in array_split
    sub_arys.append(_nx.swapaxes(sary[st:end], axis, 0))
TypeError: slice indices must be integers or None or have an __index__ method

Have you meet this problem before?

**Comment by cvqluu** [comment] 2020-10-21 08:05
Should be fixed in 848da8f5ebdc38432f6934f8c8c0be2e888cc0a8 

Was caused by num_folds not being converted into an int from the commandline

**Closed as completed by cvqluu** 2020-10-21 08:05 UTC

**Comment by wenyuqing** [comment] 2020-10-21 08:28
Thanks a lot

**Comment by LONG520520** [comment] 2021-10-26 11:50
hello everyone:
May I share the callhome dataset? I haven't found it for nearly a year.
Thank you.
